
# version: '3.9'
# services:
#   mongodb:
#     image: mongo:5.0.0
#     container_name: mongodb
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=admin
#     ports:
#       - 27017:27017
#     healthcheck:
#       test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
#       interval: 30s
#       timeout: 10s
#       retries: 3
#     restart: unless-stopped
#     command: >
#       echo 'db.createCollection("yovend-products")' | mongo localhost:27017/test --quiet

version: '3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: GRAPHQL
    volumes:
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
